name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Checkout repository code
        run: ls -la

      - name: Install dependencies
        run: npm install
         
      # - name: Run Jest tests
      #   run: npm test

      # - name: Run Cypress tests
      #   run: npm run cypress -- run

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_NAME }}/nodejs_ci_cd:latest .
          docker push ${{ secrets.DOCKER_HUB_NAME }}/nodejs_ci_cd:latest

